site_name: RM Embedded Tutorial
site_description: RM Embedded Tutorial environment setup and verification guides
site_url: https://hkustenterprize.github.io/RM2027-Tutorial-Embedded-Docs/
repo_name: hkustenterprize/RM2027-Tutorial-Embedded-Docs
repo_url: https://github.com/hkustenterprize/RM2027-Tutorial-Embedded-Docs
edit_uri: edit/main/docs/

theme:
  name: material
  language: zh
  features:
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest

plugins:
  - search:
      lang:
        - zh
        - en

nav:
  - RM Embedded Tutorial:
      - index.md
      - 环境配置:
          - Windows: "Environment/Windows/RM Embedded Tutorial 环境配置 Windows.md"
          - macOS: "Environment/macOS/RM Embedded Tutorial 环境配置 macOS.md"
          - Linux: "Environment/Linux/RM Embedded Tutorial 环境配置 Linux.md"
          - 环境验证: "Environment/Verify/RM Embedded Tutorial 环境验证.md"

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
